name: MMOPro
depend: [Vault, WorldEdit]
main: net.ecstasygaming.MMOPro
author: Zuthara
version: 1.0.51
description: Ecstasy Gaming Custom Plugin

commands:
  item:
    default: op
    usage: Item Command
  zone:
    default: op
    usage: Zone Command